services:
  db:
    image: postgres:15
    container_name: psql_mikrotik
    restart: always
    environment:
      POSTGRES_DB: mikrotik_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
