services:
  db:
    image: postgres:latest
    container_name: psql_mikrotik
    restart: always
    environment:
      POSTGRES_DB: mikrotik
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
